# Generated by Django 3.1.7 on 2021-03-19 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cigar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Fecha')),
                ('stopped', models.IntegerField(verbose_name='evitado')),
            ],
        ),
    ]
