# Generated by Django 3.1.7 on 2021-02-20 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='cDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha publicada'),
            preserve_default=False,
        ),
    ]
